Stackdriver/agent-packaging

stackdriver-collectd-gcm.conf
This is a cherry-pick of #13 into the legacy-agent-rpm branch.
=> Add process rss metrics in Collectd config template.

stackdriver-collectd-gcm.conf
Cherry-picks #14 into the legacy rpm branch.
=> Cherry pick #14 into legacy-agent-rpm.

debian/collectd-gcm.conf.tmpl
Cherry-picks #14 into the legacy deb branch.
=> Cherry pick #14 into legacy-agent-deb.

debian/rules
Cherry-picks #17 into the legacy deb branch.
=> Cherry-picks #17 into legacy-agent-deb.

rpm/Makefile, rpm/curl-7.34.0.sha1, rpm/curl-7.52.1.sha1, rpm/stackdriver-agent, rpm/stackdriver-agent.spec
This should work now. Merging into an "official" `sles12-build` branch. Will reconcile and merge into `master` later.
=> Support for SLES 12.

deb/debian/controls/control.bionic
Adding the control file for Bionic.
=> Ubuntu 18.04 Bionic Beaver - Debian package control file

deb/debian/rules
Requires Stackdriver/collectd#144 and #54.
=> Use system libmongoc on Ubuntu Bionic.

deb/debian/rules
This is the equivalent of #48 for DEB builds.
=> Re-generate autotools scripts for DEB builds.

build/x86_64_sles12/Dockerfile
1. sles12 image moved to new repo
2. automake is no longer in that folder
=> Fix sles12 image

build/x86_64_sles15/Dockerfile
* First draft of sles15 docker files
* Fix dependencies
* Update docker file
* Fix dockerfile missing dependency
* Add automake 1.16 back
=> build dockerfiles sles15 (#63) (#65)

prepare.sh, rpm/stackdriver-agent.spec
Also trace prepare.sh execution.
=> Make RPM builds more robust against changed files.

build/x86_64_buster/Dockerfile
=> Add build Dockerfile for Debian 10.

deb/debian/controls/control.buster, deb/debian/rules
Also fix a minor warning in the Bionic build.
See Stackdriver/collectd#155.
=> Debian package control file and rules changes for Debian 10.

VERSION
Just another tiny bit of cleanup after #72.
=> Remove the VERSION variable from the VERSION file.

rpm/stackdriver-agent
This will ensure that the current config location is treated as all config files are treated (i.e., won't be overwritten when user-modified, etc).
=> Fix configuration location in the RPM spec.

VERSION
This is the first commit on the new `master` branch.
=> Bump version to 6.0.0.

build/README.md
Similar to GoogleCloudPlatform/google-fluentd#228.
=> Add a README for the build Dockerfiles directory.

build/README.md
Cherry-pick #84 into `stackdriver-agent-5.5.2`.
=> Add a README for the build Dockerfiles directory. (#84)

rpm/stackdriver-agent.spec
=> Update the stackdriver-agent service on SLES systems

build/x86_64_sles12/Dockerfile, build/x86_64_sles15/Dockerfile
=> The Herbster0815 repo used for SLES containers has changed.

build/x86_64_groovy/Dockerfile
Tested in b/169246004#comment10
=> Dockerfile for ubuntu 2010 groovy

deb/debian/stackdriver-agent.init, rpm/stackdriver-agent
Tested in below distros
-  Amazon AMI
- Debian9
- Centos7
- SLES 12
=> Enable collectdmon

build/x86_64_centos6/Dockerfile
=> Update repo URLs for the deprecated CentOS 6 repos. (#115)

rpm/Makefile
A cherry-pick of #121 into the legacy branch.
=> Update curl command to follow redirects (#121)

rpm/stackdriver-agent.spec
=> Add sysvinit-tools dependency on SLES.

build/x86_64_stretch/Dockerfile
=> Install Python 2 and Python 3 packages in Debian stretch.

build/x86_64_bullseye/Dockerfile, deb/debian/controls/control.bullseye, deb/debian/controls/control.buster, deb/debian/rules
[b/200305547](http://b/200305547)
=> Support new OS distro Debian 11 (Bullseye).

rpm/stackdriver-agent.spec
This will link against the system libcurl on all platforms.
[b/303836056](http://b/303836056)
=> Don't bundle libcurl in RPM builds.
