- deb/debian/rules
- rpm/stackdriver-agent.spec
No extra dependencies needed to bundle plugin.
> Add unixsock plugin to new build path.

- stackdriver-agent.spec
No extra dependencies needed to bundle the plugin.
> Add unixsock plugin to old rpm build path

- debian/rules
No extra dependencies needed to bundle the plugin.
> Add unixsock plugin to old debian build path

- build/x86_64_amzn-2016.09/Dockerfile
This was not needed on CentOS 6-based systems, because `rpm-build` depends on `rpm`, which provided `rpmsign`.  On CentOS 7 and company, `rpmsign` was pulled into a separate package, `rpm-sign`, which wasn't pulled in by our Amazon image.
> Add missing rpm-sign package in the Amazon image.

- rpm/stackdriver-agent
Reverts a change accidentally introduced in #5.
> Stop using LSB functions on RedHat.

- deb/debian/stackdriver-agent.init
- rpm/stackdriver-agent
This fixes the broken Amazon Linux package init script.
> Set LD_LIBRARY_PATH properly when testing the config.

- build/x86_64_bionic/Dockerfile
Adds the Dockerfile for an Ubuntu 18.04 build container.
> Add Dockerfile for Ubuntu 18.04 build container

- deb/debian/rules
While building for Ubuntu 18.04, I ran into issues with the bundled version of libmongoc and changes to the openssl API in version 1.1. This PR allows us to temporarily disable libmongoc for Bionic builds, but continue using it for other platforms.
> Disable mongodb plugin on Ubuntu 18.04 Bionic

- build/x86_64_amzn-2016.09/Dockerfile
- build/x86_64_centos6/Dockerfile
- build/x86_64_centos7/Dockerfile
This was undetected breakage from the initial migration.
> Install epel-release before anything else.

- Makefile
> Re-generate autotools scripts and install missing dependencies in the mock chroot.

- deb/Makefile
- rpm/Makefile
This is a pre-requisite for building from newer agent versions.
> Don't hard-code agent version in the Makefiles.

- rpm/Makefile
- rpm/stackdriver-agent.spec
Also cleaned up the obsolete EL5 defaults — our minimum supported version is EL6.
> Changes to support CentOS 8 packages.

- rpm/Makefile
- rpm/stackdriver-agent.spec
This subsumes #48 by doing this at build time.
> Re-generate autotools scripts for RPM builds.

- deb/Makefile
- rpm/Makefile
- rpm/stackdriver-agent
- rpm/stackdriver-agent.spec
Also make the RPM build honor the `OUTPUT_DIR` setting, and make the DEB builds a bit more uniform with the RPM ones.
This is a rebase of the `sles-build` branch on top of the latest `stackdriver-agent-5.5.2` (with version support), but with additional fixes that allow building all of the RPM packages from it. It encapsulates the SLES-specific bits into the main configs.
I will be doing some additional testing of this tomorrow, but this is ready for an initial review.
> Really support SLES 12 and SLES 15.

- deb/Makefile
- rpm/Makefile
- rpm/stackdriver-agent.spec
(It was only used for naming the source checkout directory, anyway).
> Clean up the build configs to ignore the collectd version setting.

- build/x86_64_amzn-2016.09/Dockerfile
- build/x86_64_bionic/Dockerfile
- build/x86_64_buster/Dockerfile
- build/x86_64_centos6/Dockerfile
- build/x86_64_centos7/Dockerfile
- build/x86_64_centos8/Dockerfile
- build/x86_64_jessie/Dockerfile
- build/x86_64_precise/Dockerfile
- build/x86_64_sles12/Dockerfile
- build/x86_64_sles15/Dockerfile
- build/x86_64_stretch/Dockerfile
- build/x86_64_trusty/Dockerfile
- build/x86_64_wheezy/Dockerfile
- build/x86_64_xenial/Dockerfile
- deb/debian/controls/control.base
- deb/debian/controls/control.bionic
- deb/debian/controls/control.buster
- deb/debian/controls/control.jessie
- deb/debian/controls/control.precise
- deb/debian/controls/control.stretch
- deb/debian/controls/control.xenial
- deb/debian/rules
- rpm/stackdriver-agent.spec
Confirmed on CentOS 7 that adding configs for PostgreSQL, MongoDB, Varnish, and ZooKeeper cause the agent to fail to start (expected). The other deprecated applications use generic plugins (Plugin:GenericJMX = Cassandra, HBase, Kafka, Tomcat; Plugin:cURL-JSON = CouchDB, Elasticsearch, RabbitMQ, Riak) so those will still work. 
Also confirmed that the non-deprecated 3P applications still work as expected (Apache, JVM, Memcached, MySQL, Nginx, Redis).
> Remove support for deprecated plugins

- deb/debian/stackdriver-agent.init
- rpm/stackdriver-agent
Fixes the breakage introduced by #71, and includes the following changes:
- Add ENABLE_COREFILES to the RPM script
- Use pidfile to properly manage (start/stop) the daemon in the RPM script
- Remove the now-redundant lockfile code
- Allow using /etc/default/stackdriver-agent in the RPM script
- Implement try_restart in the DEB script
- Change the RPM script to use force-reload instead of reload
- Remove unused legacy genhostid command
- Remove broken and unused collectdmon support from the DEB script
- Remove unused "wait-for-stop" functionality from the DEB script
- Remove unused "disable via defaults" functionality from the DEB script
> Unify the DEB and RPM init scripts (mostly).

- build/x86_64_bionic/Dockerfile
- build/x86_64_buster/Dockerfile
- build/x86_64_jessie/Dockerfile
- build/x86_64_precise/Dockerfile
- build/x86_64_stretch/Dockerfile
- build/x86_64_trusty/Dockerfile
- build/x86_64_wheezy/Dockerfile
- build/x86_64_xenial/Dockerfile
This allows the Debian 7 (Wheezy) container to build again.
See GoogleCloudPlatform/google-fluentd#227.
> Fix build Dockerfiles and make them uniform

- deb/debian/stackdriver-agent.init
Due to kernel constraint, it can only take less than 15 chars. Debian 10 doesn't truncate. Therefore, we truncate it ourselves
> Truncate daemon name to less than 15 characters

- build/x86_64_sles12/Dockerfile
Install libhiredis.so.0.13 in the build container as SLES 12 only has 0.13
> Fix SLES 12 Missing Dependency by using libhiredis0.13 

- build/x86_64_bionic/Dockerfile
- build/x86_64_eoan/Dockerfile
- build/x86_64_focal/Dockerfile
- deb/debian/controls/control.focal
- deb/debian/rules
Adds build container Dockerfile, control file, and updates rules file.
Also a minor cleanup of the Bionic and Eoan build containers.
> Support new OS distro Ubuntu 20.04 (Focal).

- build/x86_64_sles12/Dockerfile
- build/x86_64_sles15/Dockerfile
Properly add the repo containing the correct automake version.
Fixes build errors resulting from stale package versions, e.g.:
```
Package 'libcurl4-7.66.0-lp151.270.1.x86_64' not found.
Package 'libgcrypt20-1.8.5-lp151.161.1.x86_64' not found.
```
on SLES 15 and:
```
https://ftp.gwdg.de/pub/opensuse/repositories/home:/Herbster0815/openSUSE_Leap_15.1/noarch/automake-1.16.1-lp151.93.1.noarch.rpm
...
HTTP request sent, awaiting response... 404 Not Found
```
on SLES 12.
> Remove hard-coded package versions from SLES build Dockerfiles.

- build/x86_64_sles12/Dockerfile
- build/x86_64_sles15/Dockerfile
This pulls in #82, #96, and #97 into the stackdriver-agent-5.5.2 branch.
> Cherry-pick build Dockerfile fixes for SLES 12 and SLES 15.

- rpm/stackdriver-agent-start-service.spec
This package will start the `stackdriver-agent` service automatically when installed.
> Add an RPM helper package to automatically start the agent service.

- deb/debian/rules
- rpm/stackdriver-agent.spec
Supersedes Stackdriver/collectd#186.
> Bump DATA_MAX_NAME_LEN to 256 in Linux packages.

- collectd.conf
- deb/debian/rules
- rpm/stackdriver-agent.spec
They reference a plugin from PR Stackdriver/collectd#96 that was never merged. A couple custom builds were made with it a few years ago and if anyone is using them (not sure how to find out), they are fixed to those set images (i.e. can't upgrade to current builds).
> Remove references to nonexistent docker plugin.

- build/x86_64_groovy/Dockerfile
Using the solution from https://gitlab.archlinux.org/archlinux/archlinux-docker/-/issues/32#note_1895.
Detailed debug info is listed in: b/169246004#comment13
> Downgrade coreutils to 8.30 (from Ubuntu Focal) as 8.32 causes build path permission problem

- deb/debian/controls/control.groovy
Tested internally in b/169246004#comment16
File content is the same as control.focal
> Add control.groovy file for controlling required dependencies 

- build/x86_64_centos6/Dockerfile
CentOS 6 is now out-of-support, so the repos moved from `mirror.centos.org` to `vault.centos.org`.
> Update repo URLs for the deprecated CentOS 6 repos.

- rpm/stackdriver-agent.spec
A cherry-pick of #89 into the legacy branch.
> Update the stackdriver-agent service on SLES systems (#89)

- build/x86_64_amzn-2016.09/Dockerfile
- build/x86_64_centos6/Dockerfile
- build/x86_64_centos7/Dockerfile
- build/x86_64_centos8/Dockerfile
- Remove stray `yum update` commands
- Redirect CentOS 8 mirrors to the vault
- Fix repository name on CentOS 8
See also GoogleCloudPlatform/google-fluentd#377
> Fix CentOS/Amazon AMI build Dockerfiles.

- build/x86_64_amzn-2016.09/Dockerfile
- build/x86_64_bionic/Dockerfile
- build/x86_64_buster/Dockerfile
- build/x86_64_centos6/Dockerfile
- build/x86_64_centos7/Dockerfile
- build/x86_64_centos8/Dockerfile
- build/x86_64_jessie/Dockerfile
- build/x86_64_precise/Dockerfile
- build/x86_64_sles12/Dockerfile
- build/x86_64_sles15/Dockerfile
- build/x86_64_stretch/Dockerfile
- build/x86_64_trusty/Dockerfile
- build/x86_64_wheezy/Dockerfile
- build/x86_64_xenial/Dockerfile
This is a prerequisite for continuing work on #131.
Also restore some deprecated dependencies. This is part of the effort to switch to `master` as the source of truth for these. The dependencies are harmless, since they are not included unless explicitly enabling the plugins, but allows the legacy builds to proceed. This partially reverts #83 (only the build container part).
> Update build container Dockerfiles to allow them to build again.

- build/x86_64_amzn-2016.09/Dockerfile
- build/x86_64_centos8/Dockerfile
Also a cosmetic update to the URL in the amzn build container.
A follow-on to #132.
> Use the Python 2 libraries in the CentOS 8 build container.

- build/x86_64_amzn-2016.09/Dockerfile
Removing `yum update` in #128 caused the container to have outdated `ca-certificates`, which resulted in build failures like:
```
curl: (60) SSL certificate problem: certificate has expired
```
> Update ca-certificates in the Amazon build container.

- VERSION
- build/x86_64_amzn-2016.09/Dockerfile
- build/x86_64_bionic/Dockerfile
- build/x86_64_buster/Dockerfile
- build/x86_64_centos7/Dockerfile
- build/x86_64_centos8/Dockerfile
- build/x86_64_focal/Dockerfile
- build/x86_64_sles12/Dockerfile
- build/x86_64_sles15/Dockerfile
- deb/debian/rules
- rpm/stackdriver-agent.spec
Bump minor version to 6.3.0.
http://b/168508440
> Build both python and python3 plugins.

- build/x86_64_bionic/Dockerfile
Python 2 is just python-dev on bionic.
> Fix bionic build container.
